# This file contains a list of recipe maintainers for meta-openvino

RECIPE_MAINTAINER:pn-arm-compute-library = "Tyagi, Yogesh <yogesh.tyagi@intel.com>, Kepka, Krzysztof <krzysztof.kepka@intel.com>, Vincent Solomon, Joseph Maria Jaison <jaison.vincentsolomon@intel.com>"
RECIPE_MAINTAINER:pn-intel-openmp = "Tyagi, Yogesh <yogesh.tyagi@intel.com>, Kepka, Krzysztof <krzysztof.kepka@intel.com>, Vincent Solomon, Joseph Maria Jaison <jaison.vincentsolomon@intel.com>"
RECIPE_MAINTAINER:pn-openvino-inference-engine = "Tyagi, Yogesh <yogesh.tyagi@intel.com>, Kepka, Krzysztof <krzysztof.kepka@intel.com>, Vincent Solomon, Joseph Maria Jaison <jaison.vincentsolomon@intel.com>"
